/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UnderseamysteryiImport } from './routes/undersea_mystery_i'
import { Route as MurdermysteryiiImport } from './routes/murder_mystery_ii'
import { Route as MurdermysteryiImport } from './routes/murder_mystery_i'
import { Route as CyberpunkmysteryiiImport } from './routes/cyberpunk_mystery_ii'
import { Route as CyberpunkmysteryiImport } from './routes/cyberpunk_mystery_i'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const UnderseamysteryiRoute = UnderseamysteryiImport.update({
  path: '/undersea_mystery_i',
  getParentRoute: () => rootRoute,
} as any)

const MurdermysteryiiRoute = MurdermysteryiiImport.update({
  path: '/murder_mystery_ii',
  getParentRoute: () => rootRoute,
} as any)

const MurdermysteryiRoute = MurdermysteryiImport.update({
  path: '/murder_mystery_i',
  getParentRoute: () => rootRoute,
} as any)

const CyberpunkmysteryiiRoute = CyberpunkmysteryiiImport.update({
  path: '/cyberpunk_mystery_ii',
  getParentRoute: () => rootRoute,
} as any)

const CyberpunkmysteryiRoute = CyberpunkmysteryiImport.update({
  path: '/cyberpunk_mystery_i',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cyberpunk_mystery_i': {
      id: '/cyberpunk_mystery_i'
      path: '/cyberpunk_mystery_i'
      fullPath: '/cyberpunk_mystery_i'
      preLoaderRoute: typeof CyberpunkmysteryiImport
      parentRoute: typeof rootRoute
    }
    '/cyberpunk_mystery_ii': {
      id: '/cyberpunk_mystery_ii'
      path: '/cyberpunk_mystery_ii'
      fullPath: '/cyberpunk_mystery_ii'
      preLoaderRoute: typeof CyberpunkmysteryiiImport
      parentRoute: typeof rootRoute
    }
    '/murder_mystery_i': {
      id: '/murder_mystery_i'
      path: '/murder_mystery_i'
      fullPath: '/murder_mystery_i'
      preLoaderRoute: typeof MurdermysteryiImport
      parentRoute: typeof rootRoute
    }
    '/murder_mystery_ii': {
      id: '/murder_mystery_ii'
      path: '/murder_mystery_ii'
      fullPath: '/murder_mystery_ii'
      preLoaderRoute: typeof MurdermysteryiiImport
      parentRoute: typeof rootRoute
    }
    '/undersea_mystery_i': {
      id: '/undersea_mystery_i'
      path: '/undersea_mystery_i'
      fullPath: '/undersea_mystery_i'
      preLoaderRoute: typeof UnderseamysteryiImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cyberpunk_mystery_i': typeof CyberpunkmysteryiRoute
  '/cyberpunk_mystery_ii': typeof CyberpunkmysteryiiRoute
  '/murder_mystery_i': typeof MurdermysteryiRoute
  '/murder_mystery_ii': typeof MurdermysteryiiRoute
  '/undersea_mystery_i': typeof UnderseamysteryiRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cyberpunk_mystery_i': typeof CyberpunkmysteryiRoute
  '/cyberpunk_mystery_ii': typeof CyberpunkmysteryiiRoute
  '/murder_mystery_i': typeof MurdermysteryiRoute
  '/murder_mystery_ii': typeof MurdermysteryiiRoute
  '/undersea_mystery_i': typeof UnderseamysteryiRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/cyberpunk_mystery_i': typeof CyberpunkmysteryiRoute
  '/cyberpunk_mystery_ii': typeof CyberpunkmysteryiiRoute
  '/murder_mystery_i': typeof MurdermysteryiRoute
  '/murder_mystery_ii': typeof MurdermysteryiiRoute
  '/undersea_mystery_i': typeof UnderseamysteryiRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cyberpunk_mystery_i'
    | '/cyberpunk_mystery_ii'
    | '/murder_mystery_i'
    | '/murder_mystery_ii'
    | '/undersea_mystery_i'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cyberpunk_mystery_i'
    | '/cyberpunk_mystery_ii'
    | '/murder_mystery_i'
    | '/murder_mystery_ii'
    | '/undersea_mystery_i'
  id:
    | '__root__'
    | '/'
    | '/cyberpunk_mystery_i'
    | '/cyberpunk_mystery_ii'
    | '/murder_mystery_i'
    | '/murder_mystery_ii'
    | '/undersea_mystery_i'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CyberpunkmysteryiRoute: typeof CyberpunkmysteryiRoute
  CyberpunkmysteryiiRoute: typeof CyberpunkmysteryiiRoute
  MurdermysteryiRoute: typeof MurdermysteryiRoute
  MurdermysteryiiRoute: typeof MurdermysteryiiRoute
  UnderseamysteryiRoute: typeof UnderseamysteryiRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CyberpunkmysteryiRoute: CyberpunkmysteryiRoute,
  CyberpunkmysteryiiRoute: CyberpunkmysteryiiRoute,
  MurdermysteryiRoute: MurdermysteryiRoute,
  MurdermysteryiiRoute: MurdermysteryiiRoute,
  UnderseamysteryiRoute: UnderseamysteryiRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cyberpunk_mystery_i",
        "/cyberpunk_mystery_ii",
        "/murder_mystery_i",
        "/murder_mystery_ii",
        "/undersea_mystery_i"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/cyberpunk_mystery_i": {
      "filePath": "cyberpunk_mystery_i.tsx"
    },
    "/cyberpunk_mystery_ii": {
      "filePath": "cyberpunk_mystery_ii.tsx"
    },
    "/murder_mystery_i": {
      "filePath": "murder_mystery_i.tsx"
    },
    "/murder_mystery_ii": {
      "filePath": "murder_mystery_ii.tsx"
    },
    "/undersea_mystery_i": {
      "filePath": "undersea_mystery_i.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
